config/routes.rb
Rails.application.routes.draw do

  resources :records do
    collection do
      get 'records1'
      get 'records2'
      get 'records3'
      get 'records4'
      get 'records5'
    end
  end
  resources :pages, only: [:hello_world,:hello_jsx, :hello_js, :hello_with_input] do
    collection do
      get 'hello_world'
      get 'hello_jsx'
      get 'hello_js'
      get 'hello_with_input'
    end
  end

  root 'pages#index'

end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def hello_jsx
    @name = "JSX World"
    @next_path = hello_js_pages_path
  end

  def hello_js
    @name = "JS World"
    @next_path = hello_world_pages_path
  end

  def hello_world
    @name = "Coffee World"
    @next_path = hello_with_input_pages_path
  end

  def hello_with_input
    @name = "Changeable World"
    @next_path = records1_records_path
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
    @records = Record.all
  end

  def records1
    @records = Record.all
    @next_path = records2_records_path
  end

  def records2
    @records = Record.all
    @next_path = records3_records_path
  end

  def records3
    @records = Record.all
    @next_path = records4_records_path
  end

  def records4
    @records = Record.all
    @next_path = records5_records_path
  end

  def records5
    @records = Record.all
    @next_path = records_path
  end


  def create
    @record = Record.new(record_params)

    if @record.save
      render json: @record
    else
      render json: @record.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    head :no_content
  end

  def update
    @record = Record.find(params[:id])
    if @record.update(record_params)
      render json: @record
    else
      render json: @record.errors, status: :unprocessable_entity
    end
  end

  private

  def record_params
    params.require(:record).permit(:title, :amount, :date)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.fetch(:todo, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def file_caption file, slice: nil
    render partial: 'file_caption', locals: {file: file, slice: slice}
  end

  def component_caption component, slice: nil
    render partial: 'file_caption', locals: {component: component, slice: slice}
  end

  def view_caption view, slice: nil
    file_caption "#{Rails.root}/app/views/#{view}", slice: slice
  end

  def controller_caption controller, slice: nil
    file_caption "#{Rails.root}/app/controllers/#{controller}", slice: slice
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/application/_file_caption.html.haml
- file ||= "#{Rails.root}/app/assets/javascripts/components/#{component}"
- label = file.split("/").last
%label
  = label
  = "(excerpt)" if slice

%pre
  - lines = []
  - if file["html.haml"] || file[".coffee"]
    - lines = File.open(file).readlines
  - else
    - lines = render(file: file).split("\n").map{|a| "#{a}\n"}
  - slice ||= [0,lines.count]
  - sliced_lines = lines.send(:slice, slice[0],slice[1])
  = raw CGI::escapeHTML(sliced_lines.join)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReactDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Back",:back %> |
<%= link_to "Index", root_path %> |
<%- if @next_path ||= nil%>
  <%= link_to "Next", @next_path %>
<%- end %>

<br>
<br>
<%= yield %>
<br>
<br>

<%= link_to "Back",:back %> |
<%= link_to "Index", root_path %> |
<%- if @next_path ||= nil%>
  <%= link_to "Next", @next_path %>
<%- end %>


</body>
</html>

app/views/pages/hello_js.html.haml
= react_component 'HelloJS', name: @name

= controller_caption "pages_controller.rb", slice: [9, 6]

= view_caption "pages/hello_js.html.haml"

= component_caption 'hello_js.js'

app/views/pages/hello_jsx.html.haml
= react_component 'HelloJSX', name: @name

= controller_caption "pages_controller.rb", slice: [4,5]

= view_caption "pages/hello_jsx.html.haml"

= component_caption 'hello_jsx.js.jsx'

app/views/pages/hello_with_input.html.haml
= react_component 'HelloWithInput', name: @name

= controller_caption "pages_controller.rb", slice: [20,5]

= component_caption 'hello_with_input.coffee'

%ul
  %li
    Appart from props, the state of a component can also be used to
    customize the component rendering
  %li
    The state can be found at this.state
  %li
    In order to change the state one should call the function this.setState
  %li
    Invoking setState will make the component rerender all parts of the
    dom affected by this state change
  %li
    The ref attribute should get a function that allows us to capture the
    rendered elements at render time, so that we can use their value later
  %li
    The react events do not allways have the same semantics that we are
    used to in regular dom.
/= view_caption "pages/hello_with_input.html.haml"

app/views/pages/hello_world.html.haml
= react_component 'HelloWorld', name: @name

= controller_caption "pages_controller.rb", slice: [14,5]

= view_caption "pages/hello_world.html.haml", slice: [0,8]

= component_caption 'hello_world.coffee'

%ul
  %li
    Few attribute names are different than on regular html
    in order to avoid issues with javascript keywords (e.g. class, for)
  %li
    A component receives as arguments a hash called props
    that is available at this.props
  %li
    A component doesn't ever changes its own props
  %li
    The props are like imutable parameters that customize the component
    when rendering
  %li
    The props can be passed to the component with the
    render_component rails helper

app/views/pages/index.html.haml
%h1 Hello Worlds
%ul
  %li= link_to "Hello World JSX", hello_jsx_pages_path
  %li= link_to "Hello World JS", hello_js_pages_path
  %li= link_to "Hello World CoffeeScript", hello_world_pages_path
  %li= link_to "Hello With Input", hello_with_input_pages_path

%h1 Records
%ul
  %li= link_to "Records1 - Simple List", records1_records_path
  %li= link_to "Records2 - Add Record (controlled Compoent)", records2_records_path
  %li= link_to "Records3 - Delete Record", records3_records_path
  %li= link_to "Records4 - Edit Record (Uncontrolled Component)", records4_records_path
  %li= link_to "Records5 - Rendering  Computed Data", records5_records_path
  %li= link_to "Records - Effects", records_path

app/views/records/index.html.haml
= react_component 'Records', { data: @records }

= component_caption 'records.js.coffee'

= file_caption "#{Rails.root}/app/assets/stylesheets/records.scss", slice: [4,19]

%ul
  %li
    ReactCSSTransitionGroup may be used to animate the appearance and
    disappearance of list entries
  %li
    It can also be used with single elements or with nothing.
  %li
    It works by attaching css classes to the element during the rendering workflow
  %li
    It only works with CSS animations

app/views/records/records1.html.haml
= react_component 'Records1', { data: @records }

= controller_caption "records_controller.rb", slice: [5,4]

= view_caption "records/records1.html.haml", slice: [0,1]

= component_caption 'records1.js.coffee'

%label In JSX, the createElement would be something like:
%pre
  :escaped
    render (
      ... the code before the thead
      <thead>
        <tr>
          <th>Title'</th>
          <th>Amount</th>
        {
          this.props.data.map( record =>
            return <Record1 key={record.id}
                            record={record} />)
        }
      </thead>);

= component_caption 'record1.js.coffee'

%ul
  %li
    In coffeescript one may nest componets by using the
    React.createElement function, the props hash is passed as
    the second argument
  %li
    In JSX, the props are the tag attributes
  %li
    In coffeescript, children are the remaining arguments that come after the hash
  %li
    In JSX, they are just XML children
  %li
    Within the component, children are accessible as this.props.children
  %li
    When rendering several similar sibling components we have to use the key
    attribute so that react is able to distingish them

app/views/records/records2.html.haml
= react_component 'Records2', { data: @records }

= controller_caption "records_controller.rb", slice: [30,10]

= component_caption 'record_form.js.coffee'

= component_caption 'records2.js.coffee'

= component_caption 'record1.js.coffee'

= view_caption "records/records2.html.haml", slice: [0,1]

%ul
  %li
    The only way a child should comunicate with a parent is by calling
    callbacks that are passed as props
    %ul
      %li
        The only way a parent should communicate with its children is by
        passing props to them
  %li The record form is an example of a controlled component
  %li A controlled component has controlled inputs
  %li That is the value of its inputs is rendered by itself
  %li
    We have to change state in order to change the values of controlled inputs
  %li
    Network and bussiness logic should be encapsulated in appropriate modules
  %li
    This example is too small to bother doing so

app/views/records/records3.html.haml
= react_component 'Records3', { data: @records }

= controller_caption "records_controller.rb", slice: [40,6]

= component_caption 'record3.js.coffee'

= component_caption 'records3.js.coffee'

%h3 Repeat with me:
%ul
  %li
    The only way a child should comunicate with a parent is by calling
    callbacks that are passed as props
  %li
    The only way a parent should communicate with its children is by
    passing props to them

app/views/records/records4.html.haml
= react_component 'Records4', { data: @records }

= controller_caption "records_controller.rb", slice: [46,9]

= component_caption 'record.js.coffee'

= component_caption 'records4.js.coffee'

%ul
  %li The edit form is an uncontrolled component
  %li It has no control over the values of its inputs
  %li It gets references to its inputs when rendering them
  %li It stores these references in order to later access the values of the inputs

app/views/records/records5.html.haml
= react_component 'Records5', { data: @records }

= component_caption 'amount_box.js.coffee'

= component_caption 'records5.js.coffee'

%ul
  %li
    Functions depending on state may be used to calculate values that should
    change when the state changes
    

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>